alias: Living Room Ceiling Fan
description: ''
triggers:
  - trigger: state
    entity_id:
      - sensor.fan_speed_state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.fan_speed_state
            state:
              - '1.0'
        sequence:
          - action: fan.set_percentage
            metadata: {}
            data:
              percentage: 33
            target:
              entity_id: fan.ceiling_fan
      - conditions:
          - condition: state
            entity_id: sensor.fan_speed_state
            state:
              - '2.0'
        sequence:
          - action: fan.set_percentage
            metadata: {}
            target:
              entity_id: fan.ceiling_fan
            data:
              percentage: 66
      - conditions:
          - condition: state
            entity_id: sensor.fan_speed_state
            state:
              - '3.0'
        sequence:
          - action: fan.set_percentage
            metadata: {}
            target:
              entity_id: fan.ceiling_fan
            data:
              percentage: 100
      - conditions:
          - condition: state
            entity_id: sensor.fan_speed_state
            state:
              - '0.0'
        sequence:
          - action: fan.turn_off
            metadata: {}
            target:
              entity_id: fan.ceiling_fan
            data: {}
mode: single

